apiVersion: v1
kind: Service
metadata:
  name: {{ include "garf.fullname" . }}
  labels:
    {{- include "garf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.garf.server.type }}
      protocol: TCP
      name: {{ .Values.garf.server.type }}
  selector:
    {{- include "garf.selectorLabels" . | nindent 4 }}
