// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: garf.proto

package garf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Context       *FetchContext          `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	CacheOptions  *GarfCacheOptions      `protobuf:"bytes,5,opt,name=cache_options,json=cacheOptions,proto3" json:"cache_options,omitempty"`
	Simulate      bool                   `protobuf:"varint,6,opt,name=simulate,proto3" json:"simulate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_garf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FetchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FetchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FetchRequest) GetContext() *FetchContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *FetchRequest) GetCacheOptions() *GarfCacheOptions {
	if x != nil {
		return x.CacheOptions
	}
	return nil
}

func (x *FetchRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*structpb.Struct     `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_garf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *FetchResponse) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

type FetchContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueryParameters   *QueryParameters       `protobuf:"bytes,1,opt,name=query_parameters,json=queryParameters,proto3" json:"query_parameters,omitempty"`
	FetcherParameters *structpb.Struct       `protobuf:"bytes,2,opt,name=fetcher_parameters,json=fetcherParameters,proto3" json:"fetcher_parameters,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetchContext) Reset() {
	*x = FetchContext{}
	mi := &file_garf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchContext) ProtoMessage() {}

func (x *FetchContext) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchContext.ProtoReflect.Descriptor instead.
func (*FetchContext) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{2}
}

func (x *FetchContext) GetQueryParameters() *QueryParameters {
	if x != nil {
		return x.QueryParameters
	}
	return nil
}

func (x *FetchContext) GetFetcherParameters() *structpb.Struct {
	if x != nil {
		return x.FetcherParameters
	}
	return nil
}

type GarfCacheOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnableCache     bool                   `protobuf:"varint,1,opt,name=enable_cache,json=enableCache,proto3" json:"enable_cache,omitempty"`
	CacheTtlSeconds uint32                 `protobuf:"varint,2,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GarfCacheOptions) Reset() {
	*x = GarfCacheOptions{}
	mi := &file_garf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarfCacheOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarfCacheOptions) ProtoMessage() {}

func (x *GarfCacheOptions) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarfCacheOptions.ProtoReflect.Descriptor instead.
func (*GarfCacheOptions) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{3}
}

func (x *GarfCacheOptions) GetEnableCache() bool {
	if x != nil {
		return x.EnableCache
	}
	return false
}

func (x *GarfCacheOptions) GetCacheTtlSeconds() uint32 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Context       *ExecutionContext      `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	CacheOptions  *GarfCacheOptions      `protobuf:"bytes,5,opt,name=cache_options,json=cacheOptions,proto3" json:"cache_options,omitempty"`
	Simulate      bool                   `protobuf:"varint,6,opt,name=simulate,proto3" json:"simulate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_garf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExecuteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExecuteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteRequest) GetCacheOptions() *GarfCacheOptions {
	if x != nil {
		return x.CacheOptions
	}
	return nil
}

func (x *ExecuteRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

type ExecutionContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueryParameters   *QueryParameters       `protobuf:"bytes,1,opt,name=query_parameters,json=queryParameters,proto3" json:"query_parameters,omitempty"`
	FetcherParameters *structpb.Struct       `protobuf:"bytes,2,opt,name=fetcher_parameters,json=fetcherParameters,proto3" json:"fetcher_parameters,omitempty"`
	Writer            string                 `protobuf:"bytes,3,opt,name=writer,proto3" json:"writer,omitempty"`
	WriterParameters  *structpb.Struct       `protobuf:"bytes,4,opt,name=writer_parameters,json=writerParameters,proto3" json:"writer_parameters,omitempty"`
	Writers           []string               `protobuf:"bytes,5,rep,name=writers,proto3" json:"writers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_garf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionContext) GetQueryParameters() *QueryParameters {
	if x != nil {
		return x.QueryParameters
	}
	return nil
}

func (x *ExecutionContext) GetFetcherParameters() *structpb.Struct {
	if x != nil {
		return x.FetcherParameters
	}
	return nil
}

func (x *ExecutionContext) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *ExecutionContext) GetWriterParameters() *structpb.Struct {
	if x != nil {
		return x.WriterParameters
	}
	return nil
}

func (x *ExecutionContext) GetWriters() []string {
	if x != nil {
		return x.Writers
	}
	return nil
}

type QueryParameters struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Macro          *structpb.Struct       `protobuf:"bytes,1,opt,name=macro,proto3" json:"macro,omitempty"`
	Template       *structpb.Struct       `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	MacroExpansion bool                   `protobuf:"varint,3,opt,name=macro_expansion,json=macroExpansion,proto3" json:"macro_expansion,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryParameters) Reset() {
	*x = QueryParameters{}
	mi := &file_garf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameters) ProtoMessage() {}

func (x *QueryParameters) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParameters.ProtoReflect.Descriptor instead.
func (*QueryParameters) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{6}
}

func (x *QueryParameters) GetMacro() *structpb.Struct {
	if x != nil {
		return x.Macro
	}
	return nil
}

func (x *QueryParameters) GetTemplate() *structpb.Struct {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *QueryParameters) GetMacroExpansion() bool {
	if x != nil {
		return x.MacroExpansion
	}
	return false
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_garf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

// Batch Execution
type QueryDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDefinition) Reset() {
	*x = QueryDefinition{}
	mi := &file_garf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDefinition) ProtoMessage() {}

func (x *QueryDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDefinition.ProtoReflect.Descriptor instead.
func (*QueryDefinition) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{8}
}

func (x *QueryDefinition) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QueryDefinition) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ExecuteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Batch         []*QueryDefinition     `protobuf:"bytes,2,rep,name=batch,proto3" json:"batch,omitempty"`
	Context       *ExecutionContext      `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	CacheOptions  *GarfCacheOptions      `protobuf:"bytes,4,opt,name=cache_options,json=cacheOptions,proto3" json:"cache_options,omitempty"`
	Simulate      bool                   `protobuf:"varint,5,opt,name=simulate,proto3" json:"simulate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchRequest) Reset() {
	*x = ExecuteBatchRequest{}
	mi := &file_garf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchRequest) ProtoMessage() {}

func (x *ExecuteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBatchRequest) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteBatchRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExecuteBatchRequest) GetBatch() []*QueryDefinition {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *ExecuteBatchRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteBatchRequest) GetCacheOptions() *GarfCacheOptions {
	if x != nil {
		return x.CacheOptions
	}
	return nil
}

func (x *ExecuteBatchRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

type ExecuteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchResponse) Reset() {
	*x = ExecuteBatchResponse{}
	mi := &file_garf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchResponse) ProtoMessage() {}

func (x *ExecuteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBatchResponse) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteBatchResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

// Workflow
type FetcherInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetcherInfo) Reset() {
	*x = FetcherInfo{}
	mi := &file_garf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetcherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetcherInfo) ProtoMessage() {}

func (x *FetcherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetcherInfo.ProtoReflect.Descriptor instead.
func (*FetcherInfo) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{11}
}

func (x *FetcherInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetcherInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type WorkflowMetadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RequiredGarfVersion string                 `protobuf:"bytes,3,opt,name=required_garf_version,json=requiredGarfVersion,proto3" json:"required_garf_version,omitempty"`
	RequiredFetchers    []*FetcherInfo         `protobuf:"bytes,4,rep,name=required_fetchers,json=requiredFetchers,proto3" json:"required_fetchers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkflowMetadata) Reset() {
	*x = WorkflowMetadata{}
	mi := &file_garf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowMetadata) ProtoMessage() {}

func (x *WorkflowMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowMetadata.ProtoReflect.Descriptor instead.
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{12}
}

func (x *WorkflowMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkflowMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowMetadata) GetRequiredGarfVersion() string {
	if x != nil {
		return x.RequiredGarfVersion
	}
	return ""
}

func (x *WorkflowMetadata) GetRequiredFetchers() []*FetcherInfo {
	if x != nil {
		return x.RequiredFetchers
	}
	return nil
}

type WorkflowStep struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Fetcher           string                 `protobuf:"bytes,1,opt,name=fetcher,proto3" json:"fetcher,omitempty"`
	Alias             string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Queries           []*QueryDefinition     `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	QueryParameters   *QueryParameters       `protobuf:"bytes,4,opt,name=query_parameters,json=queryParameters,proto3" json:"query_parameters,omitempty"`
	FetcherParameters *structpb.Struct       `protobuf:"bytes,5,opt,name=fetcher_parameters,json=fetcherParameters,proto3" json:"fetcher_parameters,omitempty"`
	Writer            string                 `protobuf:"bytes,6,opt,name=writer,proto3" json:"writer,omitempty"`
	WriterParameters  *structpb.Struct       `protobuf:"bytes,7,opt,name=writer_parameters,json=writerParameters,proto3" json:"writer_parameters,omitempty"`
	ParallelThreshold uint32                 `protobuf:"varint,8,opt,name=parallel_threshold,json=parallelThreshold,proto3" json:"parallel_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_garf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{13}
}

func (x *WorkflowStep) GetFetcher() string {
	if x != nil {
		return x.Fetcher
	}
	return ""
}

func (x *WorkflowStep) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *WorkflowStep) GetQueries() []*QueryDefinition {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *WorkflowStep) GetQueryParameters() *QueryParameters {
	if x != nil {
		return x.QueryParameters
	}
	return nil
}

func (x *WorkflowStep) GetFetcherParameters() *structpb.Struct {
	if x != nil {
		return x.FetcherParameters
	}
	return nil
}

func (x *WorkflowStep) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *WorkflowStep) GetWriterParameters() *structpb.Struct {
	if x != nil {
		return x.WriterParameters
	}
	return nil
}

func (x *WorkflowStep) GetParallelThreshold() uint32 {
	if x != nil {
		return x.ParallelThreshold
	}
	return 0
}

type ConfigMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMetadata) Reset() {
	*x = ConfigMetadata{}
	mi := &file_garf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMetadata) ProtoMessage() {}

func (x *ConfigMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMetadata.ProtoReflect.Descriptor instead.
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Config struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata         *ConfigMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	GlobalParameters *ExecutionContext      `protobuf:"bytes,3,opt,name=global_parameters,json=globalParameters,proto3" json:"global_parameters,omitempty"`
	Sources          *structpb.Struct       `protobuf:"bytes,4,opt,name=sources,proto3" json:"sources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_garf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{15}
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetMetadata() *ConfigMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Config) GetGlobalParameters() *ExecutionContext {
	if x != nil {
		return x.GlobalParameters
	}
	return nil
}

func (x *Config) GetSources() *structpb.Struct {
	if x != nil {
		return x.Sources
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Steps         []*WorkflowStep        `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Metadata      *WorkflowMetadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_garf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{16}
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Workflow) GetMetadata() *WorkflowMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Workflow) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ExecuteWorkflowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Workflow        *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	SelectedAliases []string               `protobuf:"bytes,2,rep,name=selected_aliases,json=selectedAliases,proto3" json:"selected_aliases,omitempty"`
	SkippedAliases  []string               `protobuf:"bytes,3,rep,name=skipped_aliases,json=skippedAliases,proto3" json:"skipped_aliases,omitempty"`
	Config          *Config                `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Context         *ExecutionContext      `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	CacheOptions    *GarfCacheOptions      `protobuf:"bytes,6,opt,name=cache_options,json=cacheOptions,proto3" json:"cache_options,omitempty"`
	Simulate        bool                   `protobuf:"varint,7,opt,name=simulate,proto3" json:"simulate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_garf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteWorkflowRequest) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetSelectedAliases() []string {
	if x != nil {
		return x.SelectedAliases
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetSkippedAliases() []string {
	if x != nil {
		return x.SkippedAliases
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetCacheOptions() *GarfCacheOptions {
	if x != nil {
		return x.CacheOptions
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_garf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteWorkflowResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

// List
type ListFetchersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FetcherInfo         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFetchersResponse) Reset() {
	*x = ListFetchersResponse{}
	mi := &file_garf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFetchersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFetchersResponse) ProtoMessage() {}

func (x *ListFetchersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFetchersResponse.ProtoReflect.Descriptor instead.
func (*ListFetchersResponse) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{19}
}

func (x *ListFetchersResponse) GetResults() []*FetcherInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListExecutorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutorsResponse) Reset() {
	*x = ListExecutorsResponse{}
	mi := &file_garf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutorsResponse) ProtoMessage() {}

func (x *ListExecutorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutorsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutorsResponse) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{20}
}

func (x *ListExecutorsResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

// Info
type GarfVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GarfVersion) Reset() {
	*x = GarfVersion{}
	mi := &file_garf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarfVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarfVersion) ProtoMessage() {}

func (x *GarfVersion) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarfVersion.ProtoReflect.Descriptor instead.
func (*GarfVersion) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{21}
}

func (x *GarfVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GarfInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutorsVersion string                 `protobuf:"bytes,1,opt,name=executors_version,json=executorsVersion,proto3" json:"executors_version,omitempty"`
	CoreVersion      string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	IoVersion        string                 `protobuf:"bytes,3,opt,name=io_version,json=ioVersion,proto3" json:"io_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GarfInfo) Reset() {
	*x = GarfInfo{}
	mi := &file_garf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GarfInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GarfInfo) ProtoMessage() {}

func (x *GarfInfo) ProtoReflect() protoreflect.Message {
	mi := &file_garf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GarfInfo.ProtoReflect.Descriptor instead.
func (*GarfInfo) Descriptor() ([]byte, []int) {
	return file_garf_proto_rawDescGZIP(), []int{22}
}

func (x *GarfInfo) GetExecutorsVersion() string {
	if x != nil {
		return x.ExecutorsVersion
	}
	return ""
}

func (x *GarfInfo) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *GarfInfo) GetIoVersion() string {
	if x != nil {
		return x.IoVersion
	}
	return ""
}

var File_garf_proto protoreflect.FileDescriptor

const file_garf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"garf.proto\x12\x04garf\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd9\x01\n" +
	"\fFetchRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12,\n" +
	"\acontext\x18\x04 \x01(\v2\x12.garf.FetchContextR\acontext\x12;\n" +
	"\rcache_options\x18\x05 \x01(\v2\x16.garf.GarfCacheOptionsR\fcacheOptions\x12\x1a\n" +
	"\bsimulate\x18\x06 \x01(\bR\bsimulate\"V\n" +
	"\rFetchResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12+\n" +
	"\x04rows\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x04rows\"\x98\x01\n" +
	"\fFetchContext\x12@\n" +
	"\x10query_parameters\x18\x01 \x01(\v2\x15.garf.QueryParametersR\x0fqueryParameters\x12F\n" +
	"\x12fetcher_parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x11fetcherParameters\"a\n" +
	"\x10GarfCacheOptions\x12!\n" +
	"\fenable_cache\x18\x01 \x01(\bR\venableCache\x12*\n" +
	"\x11cache_ttl_seconds\x18\x02 \x01(\rR\x0fcacheTtlSeconds\"\xdf\x01\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x120\n" +
	"\acontext\x18\x04 \x01(\v2\x16.garf.ExecutionContextR\acontext\x12;\n" +
	"\rcache_options\x18\x05 \x01(\v2\x16.garf.GarfCacheOptionsR\fcacheOptions\x12\x1a\n" +
	"\bsimulate\x18\x06 \x01(\bR\bsimulate\"\x94\x02\n" +
	"\x10ExecutionContext\x12@\n" +
	"\x10query_parameters\x18\x01 \x01(\v2\x15.garf.QueryParametersR\x0fqueryParameters\x12F\n" +
	"\x12fetcher_parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x11fetcherParameters\x12\x16\n" +
	"\x06writer\x18\x03 \x01(\tR\x06writer\x12D\n" +
	"\x11writer_parameters\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x10writerParameters\x12\x18\n" +
	"\awriters\x18\x05 \x03(\tR\awriters\"\x9e\x01\n" +
	"\x0fQueryParameters\x12-\n" +
	"\x05macro\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05macro\x123\n" +
	"\btemplate\x18\x02 \x01(\v2\x17.google.protobuf.StructR\btemplate\x12'\n" +
	"\x0fmacro_expansion\x18\x03 \x01(\bR\x0emacroExpansion\"+\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults\";\n" +
	"\x0fQueryDefinition\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xe5\x01\n" +
	"\x13ExecuteBatchRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12+\n" +
	"\x05batch\x18\x02 \x03(\v2\x15.garf.QueryDefinitionR\x05batch\x120\n" +
	"\acontext\x18\x03 \x01(\v2\x16.garf.ExecutionContextR\acontext\x12;\n" +
	"\rcache_options\x18\x04 \x01(\v2\x16.garf.GarfCacheOptionsR\fcacheOptions\x12\x1a\n" +
	"\bsimulate\x18\x05 \x01(\bR\bsimulate\"0\n" +
	"\x14ExecuteBatchResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults\";\n" +
	"\vFetcherInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xc2\x01\n" +
	"\x10WorkflowMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x122\n" +
	"\x15required_garf_version\x18\x03 \x01(\tR\x13requiredGarfVersion\x12>\n" +
	"\x11required_fetchers\x18\x04 \x03(\v2\x11.garf.FetcherInfoR\x10requiredFetchers\"\x86\x03\n" +
	"\fWorkflowStep\x12\x18\n" +
	"\afetcher\x18\x01 \x01(\tR\afetcher\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12/\n" +
	"\aqueries\x18\x03 \x03(\v2\x15.garf.QueryDefinitionR\aqueries\x12@\n" +
	"\x10query_parameters\x18\x04 \x01(\v2\x15.garf.QueryParametersR\x0fqueryParameters\x12F\n" +
	"\x12fetcher_parameters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x11fetcherParameters\x12\x16\n" +
	"\x06writer\x18\x06 \x01(\tR\x06writer\x12D\n" +
	"\x11writer_parameters\x18\a \x01(\v2\x17.google.protobuf.StructR\x10writerParameters\x12-\n" +
	"\x12parallel_threshold\x18\b \x01(\rR\x11parallelThreshold\"L\n" +
	"\x0eConfigMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xc6\x01\n" +
	"\x06Config\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.garf.ConfigMetadataR\bmetadata\x12C\n" +
	"\x11global_parameters\x18\x03 \x01(\v2\x16.garf.ExecutionContextR\x10globalParameters\x121\n" +
	"\asources\x18\x04 \x01(\v2\x17.google.protobuf.StructR\asources\"\x94\x01\n" +
	"\bWorkflow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x05steps\x18\x02 \x03(\v2\x12.garf.WorkflowStepR\x05steps\x122\n" +
	"\bmetadata\x18\x03 \x01(\v2\x16.garf.WorkflowMetadataR\bmetadata\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\"\xc9\x02\n" +
	"\x16ExecuteWorkflowRequest\x12*\n" +
	"\bworkflow\x18\x01 \x01(\v2\x0e.garf.WorkflowR\bworkflow\x12)\n" +
	"\x10selected_aliases\x18\x02 \x03(\tR\x0fselectedAliases\x12'\n" +
	"\x0fskipped_aliases\x18\x03 \x03(\tR\x0eskippedAliases\x12$\n" +
	"\x06config\x18\x04 \x01(\v2\f.garf.ConfigR\x06config\x120\n" +
	"\acontext\x18\x05 \x01(\v2\x16.garf.ExecutionContextR\acontext\x12;\n" +
	"\rcache_options\x18\x06 \x01(\v2\x16.garf.GarfCacheOptionsR\fcacheOptions\x12\x1a\n" +
	"\bsimulate\x18\a \x01(\bR\bsimulate\"3\n" +
	"\x17ExecuteWorkflowResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults\"C\n" +
	"\x14ListFetchersResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.garf.FetcherInfoR\aresults\"1\n" +
	"\x15ListExecutorsResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults\"'\n" +
	"\vGarfVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"y\n" +
	"\bGarfInfo\x12+\n" +
	"\x11executors_version\x18\x01 \x01(\tR\x10executorsVersion\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x1d\n" +
	"\n" +
	"io_version\x18\x03 \x01(\tR\tioVersion2\x94\x04\n" +
	"\vGarfService\x128\n" +
	"\aExecute\x12\x14.garf.ExecuteRequest\x1a\x15.garf.ExecuteResponse\"\x00\x12G\n" +
	"\fExecuteBatch\x12\x19.garf.ExecuteBatchRequest\x1a\x1a.garf.ExecuteBatchResponse\"\x00\x12P\n" +
	"\x0fExecuteWorkflow\x12\x1c.garf.ExecuteWorkflowRequest\x1a\x1d.garf.ExecuteWorkflowResponse\"\x00\x122\n" +
	"\x05Fetch\x12\x12.garf.FetchRequest\x1a\x13.garf.FetchResponse\"\x00\x129\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\x11.garf.GarfVersion\"\x00\x123\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a\x0e.garf.GarfInfo\"\x00\x12D\n" +
	"\fListFetchers\x12\x16.google.protobuf.Empty\x1a\x1a.garf.ListFetchersResponse\"\x00\x12F\n" +
	"\rListExecutors\x12\x16.google.protobuf.Empty\x1a\x1b.garf.ListExecutorsResponse\"\x00B!Z\x1fgithub.com/google/garf/sdk/garfb\x06proto3"

var (
	file_garf_proto_rawDescOnce sync.Once
	file_garf_proto_rawDescData []byte
)

func file_garf_proto_rawDescGZIP() []byte {
	file_garf_proto_rawDescOnce.Do(func() {
		file_garf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garf_proto_rawDesc), len(file_garf_proto_rawDesc)))
	})
	return file_garf_proto_rawDescData
}

var file_garf_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_garf_proto_goTypes = []any{
	(*FetchRequest)(nil),            // 0: garf.FetchRequest
	(*FetchResponse)(nil),           // 1: garf.FetchResponse
	(*FetchContext)(nil),            // 2: garf.FetchContext
	(*GarfCacheOptions)(nil),        // 3: garf.GarfCacheOptions
	(*ExecuteRequest)(nil),          // 4: garf.ExecuteRequest
	(*ExecutionContext)(nil),        // 5: garf.ExecutionContext
	(*QueryParameters)(nil),         // 6: garf.QueryParameters
	(*ExecuteResponse)(nil),         // 7: garf.ExecuteResponse
	(*QueryDefinition)(nil),         // 8: garf.QueryDefinition
	(*ExecuteBatchRequest)(nil),     // 9: garf.ExecuteBatchRequest
	(*ExecuteBatchResponse)(nil),    // 10: garf.ExecuteBatchResponse
	(*FetcherInfo)(nil),             // 11: garf.FetcherInfo
	(*WorkflowMetadata)(nil),        // 12: garf.WorkflowMetadata
	(*WorkflowStep)(nil),            // 13: garf.WorkflowStep
	(*ConfigMetadata)(nil),          // 14: garf.ConfigMetadata
	(*Config)(nil),                  // 15: garf.Config
	(*Workflow)(nil),                // 16: garf.Workflow
	(*ExecuteWorkflowRequest)(nil),  // 17: garf.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil), // 18: garf.ExecuteWorkflowResponse
	(*ListFetchersResponse)(nil),    // 19: garf.ListFetchersResponse
	(*ListExecutorsResponse)(nil),   // 20: garf.ListExecutorsResponse
	(*GarfVersion)(nil),             // 21: garf.GarfVersion
	(*GarfInfo)(nil),                // 22: garf.GarfInfo
	(*structpb.Struct)(nil),         // 23: google.protobuf.Struct
	(*emptypb.Empty)(nil),           // 24: google.protobuf.Empty
}
var file_garf_proto_depIdxs = []int32{
	2,  // 0: garf.FetchRequest.context:type_name -> garf.FetchContext
	3,  // 1: garf.FetchRequest.cache_options:type_name -> garf.GarfCacheOptions
	23, // 2: garf.FetchResponse.rows:type_name -> google.protobuf.Struct
	6,  // 3: garf.FetchContext.query_parameters:type_name -> garf.QueryParameters
	23, // 4: garf.FetchContext.fetcher_parameters:type_name -> google.protobuf.Struct
	5,  // 5: garf.ExecuteRequest.context:type_name -> garf.ExecutionContext
	3,  // 6: garf.ExecuteRequest.cache_options:type_name -> garf.GarfCacheOptions
	6,  // 7: garf.ExecutionContext.query_parameters:type_name -> garf.QueryParameters
	23, // 8: garf.ExecutionContext.fetcher_parameters:type_name -> google.protobuf.Struct
	23, // 9: garf.ExecutionContext.writer_parameters:type_name -> google.protobuf.Struct
	23, // 10: garf.QueryParameters.macro:type_name -> google.protobuf.Struct
	23, // 11: garf.QueryParameters.template:type_name -> google.protobuf.Struct
	8,  // 12: garf.ExecuteBatchRequest.batch:type_name -> garf.QueryDefinition
	5,  // 13: garf.ExecuteBatchRequest.context:type_name -> garf.ExecutionContext
	3,  // 14: garf.ExecuteBatchRequest.cache_options:type_name -> garf.GarfCacheOptions
	11, // 15: garf.WorkflowMetadata.required_fetchers:type_name -> garf.FetcherInfo
	8,  // 16: garf.WorkflowStep.queries:type_name -> garf.QueryDefinition
	6,  // 17: garf.WorkflowStep.query_parameters:type_name -> garf.QueryParameters
	23, // 18: garf.WorkflowStep.fetcher_parameters:type_name -> google.protobuf.Struct
	23, // 19: garf.WorkflowStep.writer_parameters:type_name -> google.protobuf.Struct
	14, // 20: garf.Config.metadata:type_name -> garf.ConfigMetadata
	5,  // 21: garf.Config.global_parameters:type_name -> garf.ExecutionContext
	23, // 22: garf.Config.sources:type_name -> google.protobuf.Struct
	13, // 23: garf.Workflow.steps:type_name -> garf.WorkflowStep
	12, // 24: garf.Workflow.metadata:type_name -> garf.WorkflowMetadata
	16, // 25: garf.ExecuteWorkflowRequest.workflow:type_name -> garf.Workflow
	15, // 26: garf.ExecuteWorkflowRequest.config:type_name -> garf.Config
	5,  // 27: garf.ExecuteWorkflowRequest.context:type_name -> garf.ExecutionContext
	3,  // 28: garf.ExecuteWorkflowRequest.cache_options:type_name -> garf.GarfCacheOptions
	11, // 29: garf.ListFetchersResponse.results:type_name -> garf.FetcherInfo
	4,  // 30: garf.GarfService.Execute:input_type -> garf.ExecuteRequest
	9,  // 31: garf.GarfService.ExecuteBatch:input_type -> garf.ExecuteBatchRequest
	17, // 32: garf.GarfService.ExecuteWorkflow:input_type -> garf.ExecuteWorkflowRequest
	0,  // 33: garf.GarfService.Fetch:input_type -> garf.FetchRequest
	24, // 34: garf.GarfService.GetVersion:input_type -> google.protobuf.Empty
	24, // 35: garf.GarfService.GetInfo:input_type -> google.protobuf.Empty
	24, // 36: garf.GarfService.ListFetchers:input_type -> google.protobuf.Empty
	24, // 37: garf.GarfService.ListExecutors:input_type -> google.protobuf.Empty
	7,  // 38: garf.GarfService.Execute:output_type -> garf.ExecuteResponse
	10, // 39: garf.GarfService.ExecuteBatch:output_type -> garf.ExecuteBatchResponse
	18, // 40: garf.GarfService.ExecuteWorkflow:output_type -> garf.ExecuteWorkflowResponse
	1,  // 41: garf.GarfService.Fetch:output_type -> garf.FetchResponse
	21, // 42: garf.GarfService.GetVersion:output_type -> garf.GarfVersion
	22, // 43: garf.GarfService.GetInfo:output_type -> garf.GarfInfo
	19, // 44: garf.GarfService.ListFetchers:output_type -> garf.ListFetchersResponse
	20, // 45: garf.GarfService.ListExecutors:output_type -> garf.ListExecutorsResponse
	38, // [38:46] is the sub-list for method output_type
	30, // [30:38] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_garf_proto_init() }
func file_garf_proto_init() {
	if File_garf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garf_proto_rawDesc), len(file_garf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_garf_proto_goTypes,
		DependencyIndexes: file_garf_proto_depIdxs,
		MessageInfos:      file_garf_proto_msgTypes,
	}.Build()
	File_garf_proto = out.File
	file_garf_proto_goTypes = nil
	file_garf_proto_depIdxs = nil
}
