SELECT
  FILTER_ADVERTISER_NAME,
  FILTER_ADVERTISER,
  FILTER_ADVERTISER_CURRENCY,
  FILTER_INSERTION_ORDER_NAME,
  FILTER_INSERTION_ORDER,
  FILTER_LINE_ITEM_NAME,
  FILTER_LINE_ITEM,
  METRIC_IMPRESSIONS,
  METRIC_BILLABLE_IMPRESSIONS,
  METRIC_CLICKS,
  METRIC_CTR,
  METRIC_TOTAL_CONVERSIONS,
  METRIC_LAST_CLICKS,
  METRIC_LAST_IMPRESSIONS,
  METRIC_REVENUE_ADVERTISER,
  METRIC_MEDIA_COST_ADVERTISER,
FROM STANDARD
WHERE advertiser = {advertiser_id}
AND dataRange = LAST_7_DAYS
