// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: garf.proto

package garf

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GarfService_Execute_FullMethodName         = "/garf.GarfService/Execute"
	GarfService_ExecuteBatch_FullMethodName    = "/garf.GarfService/ExecuteBatch"
	GarfService_ExecuteWorkflow_FullMethodName = "/garf.GarfService/ExecuteWorkflow"
	GarfService_Fetch_FullMethodName           = "/garf.GarfService/Fetch"
	GarfService_GetVersion_FullMethodName      = "/garf.GarfService/GetVersion"
	GarfService_GetInfo_FullMethodName         = "/garf.GarfService/GetInfo"
	GarfService_ListFetchers_FullMethodName    = "/garf.GarfService/ListFetchers"
	GarfService_ListExecutors_FullMethodName   = "/garf.GarfService/ListExecutors"
)

// GarfServiceClient is the client API for GarfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GarfServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	ExecuteBatch(ctx context.Context, in *ExecuteBatchRequest, opts ...grpc.CallOption) (*ExecuteBatchResponse, error)
	ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowRequest, opts ...grpc.CallOption) (*ExecuteWorkflowResponse, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GarfVersion, error)
	GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GarfInfo, error)
	ListFetchers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListFetchersResponse, error)
	ListExecutors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListExecutorsResponse, error)
}

type garfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGarfServiceClient(cc grpc.ClientConnInterface) GarfServiceClient {
	return &garfServiceClient{cc}
}

func (c *garfServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, GarfService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garfServiceClient) ExecuteBatch(ctx context.Context, in *ExecuteBatchRequest, opts ...grpc.CallOption) (*ExecuteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteBatchResponse)
	err := c.cc.Invoke(ctx, GarfService_ExecuteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garfServiceClient) ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowRequest, opts ...grpc.CallOption) (*ExecuteWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteWorkflowResponse)
	err := c.cc.Invoke(ctx, GarfService_ExecuteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garfServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, GarfService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garfServiceClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GarfVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GarfVersion)
	err := c.cc.Invoke(ctx, GarfService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garfServiceClient) GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GarfInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GarfInfo)
	err := c.cc.Invoke(ctx, GarfService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garfServiceClient) ListFetchers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListFetchersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFetchersResponse)
	err := c.cc.Invoke(ctx, GarfService_ListFetchers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garfServiceClient) ListExecutors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListExecutorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutorsResponse)
	err := c.cc.Invoke(ctx, GarfService_ListExecutors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GarfServiceServer is the server API for GarfService service.
// All implementations must embed UnimplementedGarfServiceServer
// for forward compatibility.
type GarfServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	ExecuteBatch(context.Context, *ExecuteBatchRequest) (*ExecuteBatchResponse, error)
	ExecuteWorkflow(context.Context, *ExecuteWorkflowRequest) (*ExecuteWorkflowResponse, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	GetVersion(context.Context, *emptypb.Empty) (*GarfVersion, error)
	GetInfo(context.Context, *emptypb.Empty) (*GarfInfo, error)
	ListFetchers(context.Context, *emptypb.Empty) (*ListFetchersResponse, error)
	ListExecutors(context.Context, *emptypb.Empty) (*ListExecutorsResponse, error)
	mustEmbedUnimplementedGarfServiceServer()
}

// UnimplementedGarfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGarfServiceServer struct{}

func (UnimplementedGarfServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedGarfServiceServer) ExecuteBatch(context.Context, *ExecuteBatchRequest) (*ExecuteBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteBatch not implemented")
}
func (UnimplementedGarfServiceServer) ExecuteWorkflow(context.Context, *ExecuteWorkflowRequest) (*ExecuteWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteWorkflow not implemented")
}
func (UnimplementedGarfServiceServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedGarfServiceServer) GetVersion(context.Context, *emptypb.Empty) (*GarfVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedGarfServiceServer) GetInfo(context.Context, *emptypb.Empty) (*GarfInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedGarfServiceServer) ListFetchers(context.Context, *emptypb.Empty) (*ListFetchersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFetchers not implemented")
}
func (UnimplementedGarfServiceServer) ListExecutors(context.Context, *emptypb.Empty) (*ListExecutorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutors not implemented")
}
func (UnimplementedGarfServiceServer) mustEmbedUnimplementedGarfServiceServer() {}
func (UnimplementedGarfServiceServer) testEmbeddedByValue()                     {}

// UnsafeGarfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GarfServiceServer will
// result in compilation errors.
type UnsafeGarfServiceServer interface {
	mustEmbedUnimplementedGarfServiceServer()
}

func RegisterGarfServiceServer(s grpc.ServiceRegistrar, srv GarfServiceServer) {
	// If the following call panics, it indicates UnimplementedGarfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GarfService_ServiceDesc, srv)
}

func _GarfService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarfService_ExecuteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).ExecuteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_ExecuteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).ExecuteBatch(ctx, req.(*ExecuteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarfService_ExecuteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).ExecuteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_ExecuteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).ExecuteWorkflow(ctx, req.(*ExecuteWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarfService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarfService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarfService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).GetInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarfService_ListFetchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).ListFetchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_ListFetchers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).ListFetchers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarfService_ListExecutors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarfServiceServer).ListExecutors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarfService_ListExecutors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarfServiceServer).ListExecutors(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GarfService_ServiceDesc is the grpc.ServiceDesc for GarfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GarfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "garf.GarfService",
	HandlerType: (*GarfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _GarfService_Execute_Handler,
		},
		{
			MethodName: "ExecuteBatch",
			Handler:    _GarfService_ExecuteBatch_Handler,
		},
		{
			MethodName: "ExecuteWorkflow",
			Handler:    _GarfService_ExecuteWorkflow_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _GarfService_Fetch_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _GarfService_GetVersion_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _GarfService_GetInfo_Handler,
		},
		{
			MethodName: "ListFetchers",
			Handler:    _GarfService_ListFetchers_Handler,
		},
		{
			MethodName: "ListExecutors",
			Handler:    _GarfService_ListExecutors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "garf.proto",
}
