[package]
name = "garf"
version = "0.0.1"
description = "Rust SDK and CLI for garf"
license = "Apache-2.0"
repository = "https://github.com/google/garf/sdk/rust"
authors = ["Andrei Markin"]
readme = "README.md"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "garf"
path = "src/main.rs"
bench = false

[dependencies]
prost = "0.14.4"
prost-types = "0.14.4"
tokio = { version = "1.53.1", features = ["full"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
opentelemetry = { version = "0.28", features = ["metrics"] }
opentelemetry-appender-tracing = "0.28.0"
opentelemetry-otlp = { version = "0.28.0", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.28", features = ["metrics", "trace", "logs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml_bw = "2.5.8"
pbjson-types = "0.9.0"
pbjson = "0.9.0"
clap = { version = "4.6.7", features = ["derive"] }
tabled = "0.22.0"

[build-dependencies]
prost-build = "0.14.4"
tonic-prost-build = "0.14.6"
pbjson-build = "0.9.0"
