name: Run tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'libs/core/**'
      - 'libs/io/**'
      - 'libs/executors/**'
env:
  UV_SYSTEM_PYTHON: 1

permissions: {}
jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        library: [core, io, executors]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv pip install pytest coverage
      - name: Test ${{ matrix.library }}
        run: |
          uv pip install -e libs/core/.[tests,all]
          uv pip install -e libs/io/.[test,all]
          uv pip install -e libs/executors/.[tests,duckdb,all]
          cd libs/${{ matrix.library }}
          pytest tests/unit
      - name: Generate Report for ${{ matrix.library }}
        run: |
          coverage run -m pytest libs/${{ matrix.library }}/tests/unit
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv pip install pytest coverage
      - name: End-to-end tests executor
        run: |
          uv pip install -e libs/core/.[tests,all]
          uv pip install -e libs/io/.[all]
          uv pip install -e libs/executors/.[tests,all]
          cd libs/executors/
          pytest tests/end-to-end/
